name: "systemd CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  ubuntu-latest-systemd-job:
    name: "systemd docker scientificlinux ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "scientificlinux" # https://hub.docker.com/_/sl
      version: "7"
      name: "scientificlinux/systemd"
      dockerdir: "Dockerfile.sl7.systemd"      
      dockerfile: "dockerfiles"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
        systemd-analyze
    - name: "docker build scientificlinux systemd base"
      run: |
        # https://hub.docker.com/_/sl
        # docker build --rm -t local/mycontainer . --file dockerfiles/${dockerfilename} 
        docker build --rm -t ${name}:${version} . --file ${dockerdir}/${dockerfile}
        # the input device is not a TTY
        # docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 local/mycontainer
        docker run -d -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 local/mycontainer
        docker image ls
        docker container ls
    